import { ColorPalette, LayoutArchetypeId } from '../types';

export const COLOR_PALETTES: ColorPalette[] = [
  {
    id: 'oxford_blue',
    name: 'Oxford Navy & Gold',
    bg: '#0B1526',
    text: '#FAF7F2',
    primary: '#0B1526',
    secondary: '#D4AF37',
    accent: '#F3E5AB',
    border: '#C29B38',
    surface: '#13223A',
  },
  {
    id: 'archival_alabaster',
    name: 'Archival Alabaster & Ink',
    bg: '#F9F7F2',
    text: '#1C1917',
    primary: '#1C1917',
    secondary: '#57534E',
    accent: '#854D0E',
    border: '#D8D2C4',
    surface: '#FFFFFF',
  },
  {
    id: 'imperial_crimson',
    name: 'Imperial Crimson & Ivory',
    bg: '#2F0B13',
    text: '#FFFDF9',
    primary: '#2F0B13',
    secondary: '#E8C5A8',
    accent: '#D4AF37',
    border: '#B33951',
    surface: '#45121E',
  },
  {
    id: 'forest_emerald',
    name: 'Forest Emerald & Parchment',
    bg: '#0E2218',
    text: '#F5F7F2',
    primary: '#0E2218',
    secondary: '#B5CEBF',
    accent: '#D4AF37',
    border: '#4A7C64',
    surface: '#163526',
  },
  {
    id: 'terracotta_linen',
    name: 'Tuscan Terracotta & Sand',
    bg: '#6E2A17',
    text: '#FFFDF5',
    primary: '#6E2A17',
    secondary: '#FED7AA',
    accent: '#FDE68A',
    border: '#D97706',
    surface: '#85341D',
  },
  {
    id: 'midnight_obsidian',
    name: 'Midnight Obsidian & Silver',
    bg: '#121214',
    text: '#F4F4F5',
    primary: '#121214',
    secondary: '#A1A1AA',
    accent: '#E4E4E7',
    border: '#3F3F46',
    surface: '#1E1E22',
  },
  {
    id: 'gallimard_cream',
    name: 'Gallimard Cream & Carmine',
    bg: '#F8F4EA',
    text: '#1C1917',
    primary: '#991B1B',
    secondary: '#44403C',
    accent: '#7F1D1D',
    border: '#991B1B',
    surface: '#FFFFFF',
  },
  {
    id: 'swiss_vermilion',
    name: 'Swiss Stark & Vermilion',
    bg: '#FFFFFF',
    text: '#09090B',
    primary: '#E11D48',
    secondary: '#27272A',
    accent: '#E11D48',
    border: '#18181B',
    surface: '#F4F4F5',
  },
  {
    id: 'candy_coral',
    name: 'Candy Coral & Sunburst',
    bg: '#FFF7ED',
    text: '#1C1917',
    primary: '#E11D48',
    secondary: '#F59E0B',
    accent: '#FBBF24',
    border: '#FDBA74',
    surface: '#FFFFFF',
  },
  {
    id: 'storybook_sky',
    name: 'Storybook Sky & Buttercup',
    bg: '#F0F9FF',
    text: '#0C4A6E',
    primary: '#0284C7',
    secondary: '#D97706',
    accent: '#F59E0B',
    border: '#BAE6FD',
    surface: '#FFFFFF',
  },
  {
    id: 'mint_bubblegum',
    name: 'Mint Gelato & Bubblegum',
    bg: '#F0FDF4',
    text: '#14532D',
    primary: '#059669',
    secondary: '#DB2777',
    accent: '#EC4899',
    border: '#A7F3D0',
    surface: '#FFFFFF',
  },
  {
    id: 'comic_canary',
    name: 'Comic Pop Canary & Blue',
    bg: '#FEF08A',
    text: '#09090B',
    primary: '#DC2626',
    secondary: '#2563EB',
    accent: '#EAB308',
    border: '#000000',
    surface: '#FFFFFF',
  },
  {
    id: 'lavender_fairytale',
    name: 'Enchanted Lilac & Tangerine',
    bg: '#FAF5FF',
    text: '#3B0764',
    primary: '#7E22CE',
    secondary: '#EA580C',
    accent: '#F97316',
    border: '#E9D5FF',
    surface: '#FFFFFF',
  },
  {
    id: 'graeco_roman_marble',
    name: 'Athenian Marble & Bronze',
    bg: '#14171A',
    text: '#FBF8F1',
    primary: '#C5A059',
    secondary: '#8C7355',
    accent: '#E5C378',
    border: '#A38346',
    surface: '#1F2429',
  },
  {
    id: 'historical_codex',
    name: 'Antiquarian Codex & Sepia',
    bg: '#241E19',
    text: '#F5EFEB',
    primary: '#C28B53',
    secondary: '#8E7560',
    accent: '#DEB887',
    border: '#705844',
    surface: '#332B24',
  },
  {
    id: 'slavonic_cinnabar',
    name: 'Slavonic Cinnabar & Obsidian',
    bg: '#181112',
    text: '#FDFBF7',
    primary: '#DC2626',
    secondary: '#D97706',
    accent: '#F59E0B',
    border: '#991B1B',
    surface: '#2A1B1D',
  },
  {
    id: 'asian_sumie',
    name: 'Kyoto Sumi-e & Vermilion',
    bg: '#15181C',
    text: '#F7F5F0',
    primary: '#DC2626',
    secondary: '#94A3B8',
    accent: '#E2B357',
    border: '#78350F',
    surface: '#1E232A',
  },
  {
    id: 'adventure_safari',
    name: 'Expedition Khaki & Brass',
    bg: '#1E2522',
    text: '#FFFEE8',
    primary: '#EAB308',
    secondary: '#B45309',
    accent: '#F59E0B',
    border: '#78350F',
    surface: '#2D3732',
  },
];

export interface LayoutArchetypeMeta {
  id: LayoutArchetypeId;
  name: string;
  category: 'Classical' | 'Modernist' | 'Dramatic' | 'Typographic' | 'Illustrated';
  description: string;
  suggestedPaletteId: string;
  defaultFont: 'Cormorant Garamond' | 'Cinzel' | 'Bodoni Moda' | 'Newsreader' | 'Plus Jakarta Sans' | 'Sniglet' | 'Fredoka';
  defaultCrop: 'oval_cameo' | 'circle_medallion' | 'arch' | 'square_frame' | 'cloud_bubble' | 'full_bleed';
  treatment: 'etching' | 'sepia' | 'monochrome' | 'natural' | 'high_contrast' | 'duotone' | 'cartoon_pop';
}

export const LAYOUT_ARCHETYPES: LayoutArchetypeMeta[] = [
  {
    id: 'classical_graeco_roman',
    name: 'The Graeco-Roman Classical',
    category: 'Classical',
    description: 'Greek meander friezes, architectural columns, Roman laurel wreath seal, and a translucent Parian marble plaque.',
    suggestedPaletteId: 'graeco_roman_marble',
    defaultFont: 'Cinzel',
    defaultCrop: 'full_bleed',
    treatment: 'etching',
  },
  {
    id: 'historical_annals',
    name: 'The Historical Chronicle',
    category: 'Classical',
    description: 'Archival document engraving with museum docket seal, cartographic grid, and translucent aged vellum title card.',
    suggestedPaletteId: 'historical_codex',
    defaultFont: 'Newsreader',
    defaultCrop: 'full_bleed',
    treatment: 'sepia',
  },
  {
    id: 'slavonic_construct',
    name: 'The Slavonic & Cyrillic Chronicle',
    category: 'Typographic',
    description: 'Slavic folklore knotwork meets constructivist geometry with Cyrillic ligature docket and smoked obsidian slab.',
    suggestedPaletteId: 'slavonic_cinnabar',
    defaultFont: 'Bodoni Moda',
    defaultCrop: 'full_bleed',
    treatment: 'high_contrast',
  },
  {
    id: 'asian_inkwash',
    name: 'The East Asian Ink & Silk',
    category: 'Illustrated',
    description: 'Japanese sumi-e mist and Ukiyo-e atmosphere with cinnabar red seal stamp, watoji stitching, and translucent washi card.',
    suggestedPaletteId: 'asian_sumie',
    defaultFont: 'Bodoni Moda',
    defaultCrop: 'full_bleed',
    treatment: 'monochrome',
  },
  {
    id: 'adventure_pulp',
    name: 'The High Adventure Expedition',
    category: 'Dramatic',
    description: '1930s pulp adventure & expedition field log with nautical compass rose, brass rivets, and weathered field slate.',
    suggestedPaletteId: 'adventure_safari',
    defaultFont: 'Plus Jakarta Sans',
    defaultCrop: 'full_bleed',
    treatment: 'sepia',
  },
  {
    id: 'archival_monograph',
    name: 'The Archival Monograph',
    category: 'Classical',
    description: 'Museum and university press edition with delicate hairline borders, Roman capitals, and cameo etching.',
    suggestedPaletteId: 'archival_alabaster',
    defaultFont: 'Cinzel',
    defaultCrop: 'oval_cameo',
    treatment: 'etching',
  },
  {
    id: 'criterion_minimal',
    name: 'The Criterion Minimalist',
    category: 'Modernist',
    description: 'Iconic colored geometric band layout, author medallion, and refined mid-century typography.',
    suggestedPaletteId: 'oxford_blue',
    defaultFont: 'Bodoni Moda',
    defaultCrop: 'circle_medallion',
    treatment: 'sepia',
  },
  {
    id: 'folio_heritage',
    name: 'The Folio Society Gilded',
    category: 'Classical',
    description: 'Sumptuous jewel tone cloth cover with gilded ornamental framing and majestic serif typography.',
    suggestedPaletteId: 'imperial_crimson',
    defaultFont: 'Cormorant Garamond',
    defaultCrop: 'oval_cameo',
    treatment: 'sepia',
  },
  {
    id: 'cinematic_bleed',
    name: 'The Cinematic Bleed',
    category: 'Dramatic',
    description: 'Full-cover author portrait with atmospheric dark gradient overlay, expansive title, and quote blurb.',
    suggestedPaletteId: 'midnight_obsidian',
    defaultFont: 'Cormorant Garamond',
    defaultCrop: 'full_bleed',
    treatment: 'monochrome',
  },
  {
    id: 'swiss_modernist',
    name: 'The Swiss Grid Editorial',
    category: 'Modernist',
    description: 'Asymmetric editorial grid with bold sans & serif counterpoint, hairline rules, and high contrast.',
    suggestedPaletteId: 'swiss_vermilion',
    defaultFont: 'Bodoni Moda',
    defaultCrop: 'square_frame',
    treatment: 'high_contrast',
  },
  {
    id: 'woodcut_broadside',
    name: 'The Victorian Woodcut',
    category: 'Typographic',
    description: 'Ornate engraved woodcut borders, floral fleurons, and traditional hand-set press typography.',
    suggestedPaletteId: 'archival_alabaster',
    defaultFont: 'Cormorant Garamond',
    defaultCrop: 'oval_cameo',
    treatment: 'etching',
  },
  {
    id: 'faber_poetry',
    name: 'The Faber Poetry Classic',
    category: 'Modernist',
    description: 'Generous clean paperspace with an iconic patterned header band and centered delicate cameo.',
    suggestedPaletteId: 'gallimard_cream',
    defaultFont: 'Newsreader',
    defaultCrop: 'circle_medallion',
    treatment: 'monochrome',
  },
  {
    id: 'constructivist',
    name: 'The Bauhaus Constructivist',
    category: 'Modernist',
    description: 'Dynamic diagonal division and stark color blocking inspired by 1920s avant-garde book arts.',
    suggestedPaletteId: 'swiss_vermilion',
    defaultFont: 'Plus Jakarta Sans',
    defaultCrop: 'square_frame',
    treatment: 'high_contrast',
  },
  {
    id: 'storybook_whimsy',
    name: 'The Whimsical Storybook',
    category: 'Illustrated',
    description: 'Joyful scalloped borders, magical sparkling stars, and friendly storybook cartoon presentation.',
    suggestedPaletteId: 'candy_coral',
    defaultFont: 'Sniglet',
    defaultCrop: 'cloud_bubble',
    treatment: 'cartoon_pop',
  },
];
